kind: pipeline
type: docker
name: default


workspace:
  path: /myproject

steps:
  - name: install dependencies and build
    image: node:16
    commands:
      - npm install
      - npm run build
    volumes:
     - name: buildFiles
       path: /myproject/build
  
  - name: upload to s3
    image: plugins/s3
    volumes:
     - name: buildFiles
       path: /myproject/build
    settings:
      bucket: drone-react-test
      region: ap-southeast-2
      access_key:
        from_secret: access_key
      secret_key:
        from_secret: secret_key
      source: /myproject/build/**/*
      target: /

volumes:
- name: buildFiles
  temp: {}
