kind: pipeline
type: docker
name: default
environment:
  REGISTRY: 676472291562.dkr.ecr.us-east-1.amazonaws.com
  AWS_ACCESS_KEY_ID: AKIAZ3AHEADVJYHWW5XJ
  AWS_SECRET_ACCESS_KEY: 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

workspace:
  path: /myproject

steps:
  - name: build
    image: 676472291562.dkr.ecr.us-east-1.amazonaws.com/drone-runner:v1
    commands:
      - echo $AWS_ACCESS_KEY_ID:$AWS_SECRET_ACCESS_KEY | docker login -u AWS --password-stdin $REGISTRY
    #  - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REGISTRY
      - docker build -t $REGISTRY/${DRONE_REPO_NAME}:${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:8} .
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
  - name: install dependencies and build
    image: node:16
    commands:
      - npm install
      - npm run build
    volumes:
     - name: buildFiles
       path: /myproject/build
  
  - name: upload to s3
    image: plugins/s3
    volumes:
     - name: buildFiles
       path: /myproject/build
    settings:
      bucket: drone-react-test
      region: us-east-1
      access_key:
        from_secret: access_key
      secret_key:
        from_secret: secret_key
      source: /myproject/build/**/*
      target: /

volumes:
- name: buildFiles
  temp: {}
